# Generated by Django 2.2.6 on 2019-10-30 14:39

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AnswerQuest', '0006_auto_20191030_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='questions',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
